### ISSUE TITLE
Unable to attach USB to WSL-Ubuntu-22.04

### ISSUE THREAD

**Issue by SSaiPrasad7** [dorssel/usbipd-win#1003]
Hello @dorssel 

I'm attempting to connect a USB device to my WSL Ubuntu setup, but it's not working. Could you assist me with this issue? I've attached screenshots to aid in troubleshooting.

Thank you in advance 

- Windows:
![image](https://github.com/user-attachments/assets/5e230ce4-7025-4cb0-802e-aaa8f45144d8)
- WSL-Ubuntu-22.04:
![image](https://github.com/user-attachments/assets/06e98986-d781-410f-9e88-bb9f4e75f6d2)

**Comment by timsu92** [comment]
I guess Microsoft may have changed something in the new kernel. I was running on the official kernel version 5.15.133 and I'm running on a customized one with UVC camera support compiled by myself.
Maybe you can head over [Microsoft's kernel page](https://github.com/microsoft/WSL2-Linux-Kernel) and try to compile to see if the problem comes from the new kernel.

**Comment by dorssel** [comment]
> I guess Microsoft may have changed something in the new kernel.

They did, duplicate of: https://github.com/dorssel/usbipd-win/issues/995 (with solution)
