### ISSUE TITLE
Failed to attach device with busid - USB webcam problem

### ISSUE THREAD

**Issue by FilipDepta** [dorssel/usbipd-win#376]
Hi,
I refer to this issue I posted on Microsoft - not sure where I should put that.
https://github.com/microsoft/WSL/issues/8375

**Comment by dorssel** [comment]
> usbip: error: recv op_common
usbip: error: read_devbuff: failed to read: err: 0x6

This is an error from an (too?) old version of `usbip`. The last version that reported this error was Linux 4.16, see https://elixir.bootlin.com/linux/v4.16.18/source/tools/usb/usbip/src/usbip_attach.c#L162.

Since Linux 4.17 this error is no longer in the `usbip` source code.

Turns out that Ubuntu 18.04 standard kernel and tools are version 4.15, so that seems right.

Can you try installing `linux-tools-virtual-hwe-18.04` instead? That will install version 5.4 of the tools. Don't forget to run the `update-alternatives` again.

@benmcmorran 
Looks like the instructions on https://github.com/dorssel/usbipd-win/wiki/WSL-support#usbip-client-tools (which were created for Ubuntu 20.04) do not work for 18.04.

@FilipDepta 
Thanks for the report. Please let us know if the alternative package works.

**Comment by FilipDepta** [comment]
Thank you for the quick reply.

You're right - it was v4.15. I've installed the `linux-tools-virtual-hwe-18.04`, then updated-alternatives with `sudo update-alternatives --install /usr/local/bin/usbip usbip /usr/lib/linux-tools/5*/usbip 20` <- `5*` for fresh installation.

After querying with `update-alternatives --query usbip` saw there are two versions (and v4 was solved as best), so I've removed the older one with `sudo update-alternatives --remove usbip /usr/lib/linux-tools/4.15.0-176-generic/usbip`. Now querying the alternatives shows v5.

Now it came down to `Device busy (exported)` problem:
```
usbipd wsl attach --busid 1-2
usbipd: info: Using default distribution 'Ubuntu-18.04'.
usbip: error: Attach Request for 1-2 failed - Device busy (exported)

usbipd: error: Failed to attach device with busid '1-2'.
```
and the solution found [here](https://github.com/dorssel/usbipd-win/issues/304), which finally works! :D

Thank you!
