### ISSUE TITLE
Attaching mouse with usbipd causes fatal error

### ISSUE THREAD

**Issue by JagpreetGrewal** [dorssel/usbipd-win#449]
Hi,

I was curious and decided to attach my mouse with usbipd even though it already worked in my wsl Debian shell. This was a bad idea. It caused my laptop to repeatedly crash and restart until I disconnected everything besides the charger.

I also recieved the following error: ```PNP_DETECTED_FATAL_ERROR```

To fix the issue, I had to uninstall usbipd. This was the only option as connecting anything (USBs or HDMI cables) would cause my laptop to crash and restart. As a result, I could not detach my mouse through the command line as its bus-id would not show with the mouse unconnected.

Will usbipd automatically attach certain bus-id's if I were to reinstall it? I am unsure if something like this would be saved after uninstallation but I do not wish to take a chance.

**Comment by dorssel** [comment]
Crashing Windows, and errors like PNP_DETECTED_FATAL_ERROR are driver related. `usbipd` uses the drivers from VirtualBox; nothing that I can fix there. However ... when you reboot `usbipd` is not touching the device or drivers *at all*, unless you used `usbipd bind --force`. Did you? If not, then something fishy is going on. `usbipd` should not have any effect until you do an attach. A crash can happen during attach (due to flaky driver), but a reboot should not make it crash again. Again: unless you used `usbipd bind --force`.

Good news: uninstalling removes everything, even `--force`. There should not be anything persisted.
