### ISSUE TITLE
Signing cert expired?

### ISSUE THREAD

**Issue by shanselman** [dorssel/usbipd-win#47]
Has the driver signing cert expired? I'm unable to install and per these verbose logs this smells like a cert issue.

`DIFXAPP: ERROR: encountered while installing driver package 'C:\Program Files\usbipd-win\Drivers\VBoxUSB\VBoxUSB.inf'
DIFXAPP: ERROR: InstallDriverPackages failed with error 0xE0000247
DIFXAPP: RETURN: InstallDriverPackages() 3758096967 (0xE0000247)
CustomAction MsiInstallDrivers returned actual error code 1603`

**Comment by dorssel** [comment]
Update on Guess 1:
The newest VirtualBox release has a driver catalog file that is *also* signed with a Windows 10 Microsoft attestation signature. The driver we are bunding now only has that on the SYS file, not the catalog.

Update on Guess 2:
I inadvertently register the SHA-1 certificate for silent installs, but the drivers are (correctly) dual-signed with both SHA-1 and SHA-256 signatures.

Update on Guess 3:
I can confirm that the *latest* Windows 11 Insider no longer allows any install of usbipd-win 1.1.0, silent or interactive.
From: https://www.virtualbox.org/wiki/Changelog

> VirtualBox 6.1.28 (released October 19 2021)
> Windows Guest: Introduced Windows 11 guest support, including unattended installation

Note that this is talking about *guest* not *host* (which is what we do), but it is an indication...

Conclusion: I will update to the latest VirtualBox driver, and change silent install to use the SHA-256 cert. Then I will check if the latest Windows 11 Insider accepts it.

**Comment by dorssel** [comment]
I have updated the driver and certificate, but it does not work for me on Windows 11 Insider.
Artifact at: https://github.com/dorssel/usbipd-win/pull/48/checks?check_run_id=3957665556

**Comment by klaus-vb** [comment]
Can you try again with the re-packaged https://download.virtualbox.org/virtualbox/6.1.34/VirtualBox-6.1.34a-150636-Win.exe ?

This should have the driver signing issues fixed (the more annoying issue was actually an installer bug, resulting in installing the "pre-W10" cat file on Windows 10 and later). It contains the same build (all files are old, having signatures from mid March) as the original release.

It really was a nasty issue (especially as Explorer happily showed the signatures, and IIRC even signtool thought they're good). We fixed it bit by bit since your analysis, but there was always something else which didn't go as planned, rendering the fix as ineffective.

**Comment by dorssel** [comment]
@klaus-vb 
I had already fixed that. see https://github.com/dorssel/usbipd-win/releases/tag/v1.1.1.
Since then, usbipd-win already ships with the original Windows signed .cat file, instead of the re-signed (or rather, faulty doubly-signed) VBox cat file. As a consequence, we are already using what you call 6.1.34**_a_** . This issue is really closed.

**Comment by klaus-vb** [comment]
Yes, I know, but the point is that with 6.1.34a and later you shouldn't need to do .cat file surgery any more. I haven't tried usbipd-win myself so far, but I can see that all "driver level" functionality it needs are in the drivers we developed. It's nice to see that reusing our code is possible.

**Comment by dorssel** [comment]
OK, I've verified that the drivers in VirtualBox-6.1.34a are indeed byte-for-byte identical to what we already have in usbipd-win. This means that the .cat files we both use are now the same, original, Microsoft-signed .cat files. Good to know that I don't have to do the ASN.1 reconstructing again in the future!
