### ISSUE TITLE
WSL2 | Win11 - The `--distribution` flag is ignored - USB still gets attached to the default WSL distribution.

### ISSUE THREAD

**Issue by David00** [dorssel/usbipd-win#648]
Hello,

First of all, thank you for this project. It looks fantastic. I am attempting to use USB pass through on my Windows 11 machine to allow my Kali Linux WSL instance to access a USB NIC directly.  Kali Linux is not my default WSL distribution, and I am aware that Microsoft says the WSL distribution must be set as default ([step #2 here](https://learn.microsoft.com/en-us/windows/wsl/connect-usb#attach-a-usb-device))

However, when attaching the device from PowerShell, I am getting the following log message: 

```
PS C:\WINDOWS\system32> usbipd wsl attach --busid 6-1
usbipd: info: Using default WSL distribution 'Ubuntu'; specify the '--distribution' option to select a different one.
```

Here's a quick check showing the attachment worked to my default distribution named Ubuntu, followed by a WSL list:

```
PS C:\Users\david> usbipd wsl list
BUSID  VID:PID    DEVICE                                                        STATE
6-1    0e8d:7961  Generic Bluetooth Adapter, WiFi_If                            Attached - Ubuntu

PS C:\Users\david> wsl --list --verbose
  NAME          STATE           VERSION
* Ubuntu        Running         2
  kali-linux    Running         2
```

So, I detach 6-1, and then run attach, this time with the distribution flag set:

```
PS C:\WINDOWS\system32> usbipd wsl attach --busid 6-1 --distribution kali-linux
PS C:\Users\david> usbipd wsl list
BUSID  VID:PID    DEVICE                                                        STATE
6-1    0e8d:7961  Generic Bluetooth Adapter, WiFi_If                            Attached - Ubuntu
```

You can see that even though I specified kali-linux, it still shows attached to Ubuntu.  I checked `lsusb` from Ubuntu and sure enough, I see the USB ID: 

```
david@XPS:~$ lsusb
Bus 002 Device 009: ID 0e8d:7961 MediaTek Inc. Wireless_Device
```

So, it seems that the Microsoft documentation is correct, and the logged info message about using the `--distribution` flag is not. I understand that I can set my kali-linux image as default and then attach the USB.  This issue is just to point out the discrepancy between usbipd's log message and the Microsoft documentation.

I am running the following usbipd version:

```
PS C:\Users\david> usbipd --version
3.0.0+361.Branch.master.Sha.89d4b327c99a4eecc9b583e1843a428aae3c9270
```

Thanks!

**Comment by dorssel** [comment]
@benmcmorran 
Thanks for the report. I've investigated and the situation has changed since this code was written.

This is what always has been (and still is) the case:

1) All distros share the same kernel instance. This has always been the case. This means when you attach to one distribution , the device is available in all distributions.
2) (1) means: it doesn't really matter which distribution you use to attach, as the kernel is shared anyway.
3) It *does* matter to specify the distribution, since client tools must be used to tell the kernel about the new device. This client tooling must be installed on the distribution. Again, you can use either distribution, but you must tell `usbipd` which one to use.
4) (3+2) means: the attaching itself uses a specific distribution, but once attached there is no difference anymore

This is what changed with respect to earlier WSL versions:

5) Previously, each distribution had its own IP address. Now, they also all share the same network interface *and* address.
6) `usbipd` uses the source IP address to determine which distro was used to attach (even though after attachment, it doesn't really matter). This no longer works, as the distros now all share the same IP address.
7) (6) means that it is no longer possible to determine which distro was used to attach. And that isn't a problem, as it really doesn't matter.

So (conclusion):

- `usbipd wsl attach --distribution` does work correctly, it *does* use the right distro for the client tooling (just verified)
- `usbipd wsl list` can no longer tell the distros apart, and the reporting currently just lists the first (default) distro, as its IP address matches.
- I will remove reporting a specific distro for `usbipd wsl list`

PS: Long answer for my own administration. I will write a Wiki about this, some day.

Anyway: thanks again for the report.
