### ISSUE TITLE
usbipd: error: The 'wsl' subcommand has been removed.

### ISSUE THREAD

**Issue by ludy51** [dorssel/usbipd-win#796]
The latest usbipd-win4.0.0 version reported an error under the window shell, unable to add the 'wsl' parameter, so that wsl can access usb devices. If it is replaced with 3.10, no error is reported. 
System Environment: window11
=======================================
> usbipd wsl list
usbipd: error: The 'wsl' subcommand has been removed. Learn about the new syntax at https://learn.microsoft.com/windows/wsl/connect-usb#attach-a-usb-device.

**Comment by dorssel** [comment]
Use the docs in the repo for current documentation: https://github.com/dorssel/usbipd-win/wiki/WSL-support.

Your issue is about Microsoft documentation, which I do not control. I know that they are working on it, so you don't need to report it there (although that is up to you, of course). In any case, the referred to document is from the MS repo, not this one.
